# text = open("Output.csv", "r")
text = open("links.csv", "r")
# text = ''.join([i for i in text]).replace(",", "")
# text = ''.join([i for i in text]).replace(" ", "\n")
# text = ''.join([i for i in text]).replace("[", "")
# text = ''.join([i for i in text]).replace("]", "")
# text = ''.join([i for i in text]).replace("'", "")
text = ''.join([i for i in text]).replace("http:", "\nhttp:")
x = open("Output.csv","w")
x.writelines(text)
x.close()